services:
  api:
    image: jdromero9402/mlops_talleres:inference
    ports:
      - "8005:8000"
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: 0.5
    restart: "no"