[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
    "uvicorn>=0.35.0",
    "mlflow>=3.4.0",
    "boto3>=1.40.35"
]
