FROM apache/airflow:2.6.0-python3.10

# Install uv by copying static binaries from the official image (no curl)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /usr/local/bin/uvx


# Copy only project metadata to leverage Docker layer cache
COPY ./training-app/pyproject.toml ./pyproject.toml



RUN uv pip install --system .





