# app-mlops-diabetes.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-market-api
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/JonatanGallo/MLOps---Talleres.git
    targetRevision: main
    path: proyecto-4-property-market/manifests/api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true